version: '3'

volumes:
  pg_data_production:
  static_volume:

# Всё отличие — заменяем build на image и указываем, какой образ использовать
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: alexf2/taski_backend:latest
    env_file: .env
    volumes:
      - static_volume:/backend_static
  frontend:
    image: alexf2/taski_frontend:latest  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: alexf2/taski_gateway:latest  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80 

# Запускать: docker compose -f docker-compose.production.yml up 

# А потом собрать статику и закинуть на том
# docker compose -f docker-compose.production.yml exec backend python manage.py collectstatic
# docker compose -f docker-compose.production.yml exec backend cp -r /app/collected_static/. /backend_static/static/ 

# И миграции
# docker compose -f docker-compose.production.yml exec backend python manage.py migrate

# И суперюзер
# docker compose -f docker-compose.production.yml exec backend python manage.py createsuperuser

