version: '3'
# Перечень volume
volumes:
  pg_data:
  static:

networks:
  common_ydx_network:
    name: common_ydx_network

# Перечень контейнеров
services:
  # Имя и описание первого контейнера; имя выбирает разработчик. 
  # Это контейнер БД
  db:
    # Из какого образа запустить контейнер:
    image: postgres:13.10
    # Файл (или список файлов) с переменными окружения
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      common_ydx_network:
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "django_user"]
      interval: 1s
      timeout: 1s
      retries: 60

  # Имя и описание контейнера с бэкендом
  backend:
    # Из какого Dockerfile собирать образ для этого контейнера:
    build: ./backend/
    env_file: .env
     # Тут подключаем volume к backend
    volumes:
      - static:/backend_static
    # Какие контейнеры нужно запустить до старта этого контейнера:    
    networks:
      common_ydx_network:
    depends_on:
      db:
        condition: service_healthy

  # Имя третьего контейнера. Это контейнер с фронтендом
  frontend:
    env_file: .env
    build: ./frontend/ 
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    networks:
      common_ydx_network:

  gateway:
    # Сбилдить и запустить образ, 
    # описанный в Dockerfile в папке gateway
    build: ./gateway/
      # А тут подключаем volume со статикой к gateway
    volumes:
      - static:/staticfiles/
    # Ключ ports устанавливает
    # перенаправление всех запросов с порта 8000 хоста
    # на порт 80 контейнера.
    ports:
      - 8000:80 
        # порт_хоста:порт_контейнера
    networks:
      common_ydx_network:

